# ── Post-provision hook ─────────────────────────────────────────────
# Runs after `azd provision` to populate .env with provisioned values.

$ErrorActionPreference = "Stop"

Write-Host "==> Post-provision: writing .env from azd outputs..."

$Endpoint = azd env get-value endpoint 2>$null
$BingConn = azd env get-value bingConnectionId 2>$null
$Model = azd env get-value deploymentName 2>$null

if (-not $Model) { $Model = "gpt-4o" }

$EnvContent = @"
# Auto-generated by hooks/postprovision.ps1 - do not edit manually
AZURE_AI_ENDPOINT=$Endpoint
BING_CONNECTION_ID=$BingConn
MODEL_NAME=$Model
AGENT_IDS={}
"@

Set-Content -Path ".env" -Value $EnvContent -Encoding UTF8

Write-Host "==> .env written successfully."

Write-Host "==> Post-provision: installing Python dependencies..."
pip install -r requirements.txt

Write-Host "==> Post-provision: creating agent(s) via src.setup..."
python -m src.setup
